spring:
  config:
    activate:
      on-profile: prod
jwt:
  secret-key: ${JWT_SECRET}

oauth:
  kakao:
    client-id: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com