spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/musicpedia
    username: musicpedia
    password: 1234
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql: trace
  data:
    redis:
      host: localhost
      port: 6379
      password: 1234
  flyway:
    enabled: false

cloud:
  aws:
    credentials:
      access-key: ${S3_ACCESS_KEY}
      secret-key: ${S3_SECRET_KEY}
    s3:
      bucket: ${BUCKET_NAME}
    region: ap-northeast-2

jwt:
  secret-key: ${JWT_SECRET}

oauth:
  kakao:
    client-ids: ${KAKAO_CLIENT_ID}
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    client-ids: ${IOS_GOOGLE_CLIENT_ID}, ${ANDROID_GOOGLE_CLIENT_ID}
    url:
      auth: https://accounts.google.com
  apple:
    client-ids: ${APPLE_CLIENT_ID}
    url:
      auth: https://appleid.apple.com
  spotify:
    client-id: ${SPOTIFY_CLIENT_ID}
    client-secret: ${SPOTIFY_CLIENT_SECRET}
    url:
      auth: https://accounts.spotify.com
      api: https://api.spotify.com

guest:
  member-id: ${GUEST_MEMBER_ID}

client:
  minimum-compatible-version: ${MINIMUM_COMPATIBLE_VERSION}