name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Set IMAGE_VERSION from Secrets
        run: echo "IMAGE_VERSION=${{ secrets.IMAGE_VERSION }}" >> $GITHUB_ENV

      - name: Build JAR file
        run: ./gradlew build -x test

      - name: Build Docker image
        run: docker build -t ghcr.io/musicpedia/mupie-api:${{ env.IMAGE_VERSION }} .

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.CONTAINER_REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/musicpedia/mupie-api:${{ env.IMAGE_VERSION }}
