name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Build JAR file
        run: ./gradlew build -x test

      - name: Build Docker image
        run: docker build -t ghcr.io/musicpedia/mupie-api:${{ secrets.IMAGE_VERSION }} .

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CONTAINER_REGISTRY_TOKEN }}

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/musicpedia/mupie-api:${{ secrets.IMAGE_VERSION }}
